# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-16 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('has_cam', models.BooleanField(default=True)),
                ('location_img', models.CharField(blank=True, max_length=100, null=True)),
                ('location_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'boia',
            },
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nie', models.CharField(default=None, max_length=10, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('lat', models.DecimalField(decimal_places=7, default=None, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, default=None, max_digits=10)),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'centre',
            },
        ),
        migrations.CreateModel(
            name='Registre_boia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('tmp_air', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('tmp_water', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('wind_speed', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('boia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Boia')),
            ],
            options={
                'db_table': 'registre_boia',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=36, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('being_used', models.BooleanField(default=False)),
                ('centre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Centre')),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.AddField(
            model_name='boia',
            name='centre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Centre'),
        ),
    ]
