# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-02 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_public', models.BooleanField(default=False)),
                ('has_cam', models.BooleanField(default=True)),
                ('location_img', models.URLField()),
                ('location_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nif', models.CharField(max_length=8, unique=True)),
                ('description', models.CharField(max_length=5000)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('img', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='boia',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Centre'),
        ),
    ]
