# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(default='Label', max_length=30, unique=True)),
                ('synopsis', models.CharField(blank=True, max_length=1000, null=True)),
                ('href', models.CharField(default='/', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'slider',
            },
        ),
    ]
