# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-02 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160502_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boia',
            name='centre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Centre'),
        ),
        migrations.AlterModelTable(
            name='boia',
            table='boies',
        ),
        migrations.AlterModelTable(
            name='centre',
            table='centres',
        ),
    ]
