# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-16 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='label',
        ),
    ]
