# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-19 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160519_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
