# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-03 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160502_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boia',
            name='location_img',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='centre',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='centre',
            name='img',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
