# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-16 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_slider_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='btn',
            field=models.CharField(default='Més informació', max_length=100),
        ),
    ]
