# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-17 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slider_btn'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='centre',
            name='site',
            field=models.URLField(default='http://www.boiager.cat'),
        ),
    ]
