# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-03 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20160503_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
