# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-17 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160517_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
