# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-05 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_centre_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='nif',
        ),
        migrations.AddField(
            model_name='centre',
            name='nie',
            field=models.CharField(default=1234567891, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
