# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-05 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160505_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='nie',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
