# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-05 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160505_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boia',
            name='is_public',
        ),
        migrations.AddField(
            model_name='centre',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
