# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160505_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registre_boia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registre_boia',
            },
        ),
        migrations.AlterField(
            model_name='boia',
            name='location_img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centre',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='centre',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centre',
            name='nie',
            field=models.CharField(default=None, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registre_boia',
            name='boia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Boia'),
        ),
    ]
