# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160506_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(default='Label', max_length=30, unique=True)),
                ('synopsis', models.CharField(blank=True, max_length=1000, null=True)),
                ('filename', models.CharField(default='index.html', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'slider',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=36, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('being_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.AddField(
            model_name='registre_boia',
            name='tmp_air',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='registre_boia',
            name='tmp_water',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='registre_boia',
            name='wind_speed',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AlterModelTable(
            name='boia',
            table='boia',
        ),
        migrations.AlterModelTable(
            name='centre',
            table='centre',
        ),
        migrations.AddField(
            model_name='token',
            name='centre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Centre'),
        ),
    ]
