# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-08 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160506_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boia',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boia',
            name='lng',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='centre',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='centre',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='centre',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
