# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160502154303 on 2016-05-13 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160508_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registre_boia',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
